[project]
name = "P4"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "shared-utils",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
shared-utils = { path = "../../shared", editable = true }
